version: '3'

services:
  springboot-jukebox-control-settings-app-container:
    image: jukebox-control-settings:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/jukebox-control-settings-app
    ports:
      - "8080:8080"
